// ============================================================
// data.js - 둥글둥글 감정마을 게임 데이터
// 진단 기반: Big Five Factor Model (OCEAN)
// ============================================================

// ============================================================
// 🖼️ SPRITE_CONFIG — 이미지 교체 설정
// ============================================================
const SPRITE_CONFIG = {
  characters: {
    cat:      null, // 인트로 고양이
    quokka:   null, // 챕터1 쿼카 (E)
    hedgehog: null, // 챕터1 고슴도치 (E)
    beaver:   null, // 챕터2 비버 (O)
    sheep:    null, // 챕터2 아기 양 (O)
    maru:     null, // 챕터3 리트리버 (A)
    owl:      null, // 챕터3 올빼미 (A)
    raccoon:  null, // 챕터4 너구리 (C)
    squirrel: null, // 챕터4 다람쥐 (C)
    snail:    null, // 챕터5 달팽이 (N)
    frog:     null, // 챕터5 개구리 (N)
  },
  backgrounds: {
    intro:    null,
    chapter0: null, // 광장 축제
    chapter1: null, // 반짝이 숲길
    chapter2: null, // 호숫가 찻집
    chapter3: null, // 칙칙폭폭 간이역
    chapter4: null, // 비 내리는 정원
  },
};

// NPC 캐릭터 정보
const NPC_DATA = {
  cat: {
    name: '다정 고양이',
    trait: '따뜻하고 포근한 안내자',
    color: '#FFB7C5',
    cssClass: 'char-cat',
    chapter: 'intro',
  },
  quokka: {
    name: '쿼카',
    trait: '에너지 넘치고 사교적인 친구',
    color: '#FFD580',
    cssClass: 'char-quokka',
    chapter: 1,
    trait_letter: 'E',
  },
  hedgehog: {
    name: '고슴도치',
    trait: '조용하고 사려 깊은 친구',
    color: '#A0C4FF',
    cssClass: 'char-hedgehog',
    chapter: 1,
    trait_letter: 'E',
  },
  beaver: {
    name: '비버',
    trait: '꼼꼼하고 관찰력 뛰어난 친구',
    color: '#B5EAD7',
    cssClass: 'char-beaver',
    chapter: 2,
    trait_letter: 'O',
  },
  sheep: {
    name: '아기 양',
    trait: '상상력 풍부하고 몽환적인 친구',
    color: '#C9B1FF',
    cssClass: 'char-sheep',
    chapter: 2,
    trait_letter: 'O',
  },
  maru: {
    name: '리트리버 마루',
    trait: '따뜻하고 공감력 높은 친구',
    color: '#FFCBA4',
    cssClass: 'char-maru',
    chapter: 3,
    trait_letter: 'A',
  },
  owl: {
    name: '올빼미 선생님',
    trait: '논리적이고 공정한 친구',
    color: '#AED6DC',
    cssClass: 'char-owl',
    chapter: 3,
    trait_letter: 'A',
  },
  raccoon: {
    name: '너구리 역장',
    trait: '체계적이고 믿음직한 친구',
    color: '#D4A5A5',
    cssClass: 'char-raccoon',
    chapter: 4,
    trait_letter: 'C',
  },
  squirrel: {
    name: '다람쥐 여행가',
    trait: '자유롭고 즉흥적인 친구',
    color: '#FFC8A2',
    cssClass: 'char-squirrel',
    chapter: 4,
    trait_letter: 'C',
  },
  snail: {
    name: '달팽이',
    trait: '느긋하고 섬세한 친구',
    color: '#C4A882',
    cssClass: 'char-snail',
    chapter: 5,
    trait_letter: 'N',
  },
  frog: {
    name: '개구리',
    trait: '솔직하고 명랑한 친구',
    color: '#7DC87D',
    cssClass: 'char-frog',
    chapter: 5,
    trait_letter: 'N',
  },
};

// 도입부 대사 (고양이)
const INTRO_DIALOGUES = [
  '안개 낀 마을 어귀에 도착하신 걸 환영해요! 저는 이 마을을 안내하는 다정 고양이예요 🐱',
  '이 마을은 특별해요. 여기선 틀린 감정도, 이상한 성격도 없어요. 모두 다 소중하거든요 💕',
  '마을을 여행하다 보면 자연스럽게 나만의 이야기가 펼쳐질 거예요.',
  '마을 친구들이 물어보는 질문들에 솔직하게 답해주세요. 정답은 없으니까요 🌸',
  '자, 준비됐으면 광장 축제로 출발해볼까요? 쿼카와 고슴도치가 기다리고 있을 거예요!',
];

// 챕터 전환 메시지 (챕터 완료 후 → 다음 챕터 이동 시 표시)
const CHAPTER_TRANSITIONS = [
  null, // 챕터1은 인트로 후 바로 시작
  '광장 축제에서의 시간이 즐거웠나요? 이제 반짝이는 숲길로 올라가 봐요. 비버와 아기 양이 기다리고 있어요! 🌿',
  '숲길 탐험이 재미있었나요? 이제 호숫가 찻집에서 따뜻한 차 한 잔 어떨까요? 마루와 올빼미 선생님이 계세요 ☕',
  '찻집에서 마음이 따뜻해졌나요? 이제 칙칙폭폭 간이역으로 가봐요. 너구리 역장과 다람쥐 여행가가 기다려요! 🚂',
  '기차역에서의 여정을 마쳤어요. 마지막 장소, 비 내리는 정원으로 가볼까요? 달팽이와 개구리가 기다리고 있어요! 🌧️',
];

// ============================================================
// 챕터 데이터 (5챕터 × 5상황 = 25상황)
// Big Five OCEAN 기반: E(외향성), O(개방성), A(우호성), C(성실성), N(감수성)
// ============================================================
const CHAPTER_DATA = [

  // ============================
  // 챕터 1: 광장 축제 (E: 외향성)
  // ============================
  {
    id: '1-1',
    chapterIndex: 0,
    chapterType: 'E',
    chapterTitle: '광장 축제',
    chapterEmoji: '🌻',
    npcKey: 'quokka',
    npcName: '쿼카',
    narratorText: '마을 광장에 처음 도착했어요. 알록달록한 가게들이 늘어선 광장에서 쿼카와 고슴도치를 만났어요.',
    npcDialogue_low: '어... 안녕? 나는 쿼카야. 사람 많은 데서 말 거는 게 어렵지 않아? 나도 사실 처음엔 긴장했어.',
    npcDialogue_mid: '안녕! 나는 쿼카야! 오늘 처음 왔어? 마을에 온 걸 환영해! 필요한 거 있으면 말해줘 😊',
    npcDialogue_high: '안녕!! 나는 쿼카!! 와, 새 친구다!! 이름이 뭐야?? 우리 친해지자!! 마을 구경시켜줄게!!',
    questionPrompt: '어떻게 인사했어요? 🌼',
    contextForAPI: '처음 만난 낯선 사람과의 첫 인사 상황. E(외향성)이 높을수록 적극적으로 먼저 다가가고, 낮을수록 조심스럽게 인사한다.',
    nextSituationHint: '광장 한쪽에서 파티 준비 소리가 들리고, 쿼카가 주말 파티에 초대하는 상황',
  },
  {
    id: '1-2',
    chapterIndex: 0,
    chapterType: 'E',
    chapterTitle: '광장 축제',
    chapterEmoji: '🌻',
    npcKey: 'quokka',
    npcName: '쿼카',
    narratorText: '광장 한쪽에서 파티 준비 소리가 들려요! 쿼카가 신나게 달려왔어요.',
    npcDialogue_low: '이번 주말에 작은 파티를 여는데... 부담스러우면 안 와도 괜찮아. 그냥 혹시나 해서 물어보는 거야.',
    npcDialogue_mid: '이번 주말에 마을 친구들이랑 파티를 여는데 같이 올래? 맛있는 것도 많고 재미있을 거야!',
    npcDialogue_high: '파티파티!! 이번 주말에 엄청난 파티를 여는데 꼭 와야 해!! 거절하면 안 돼!! 같이 가자!!',
    questionPrompt: '파티 초대, 솔직히 어떤 마음이에요?',
    contextForAPI: '파티 초대 상황. E(외향성)이 높을수록 신나고 설레며 참여를 원하고, 낮을수록 부담스럽거나 조용히 참여할지 고민한다.',
    nextSituationHint: '광장 벤치에서 혼자 책 읽던 고슴도치가 살며시 말을 거는 상황',
  },
  {
    id: '1-3',
    chapterIndex: 0,
    chapterType: 'E',
    chapterTitle: '광장 축제',
    chapterEmoji: '🌻',
    npcKey: 'hedgehog',
    npcName: '고슴도치',
    narratorText: '광장 벤치에서 혼자 책을 읽던 고슴도치가 살며시 말을 걸었어요.',
    npcDialogue_low: '저도... 낯선 분이랑 대화하는 게 좀 어렵긴 한데. 그래도 안녕하세요.',
    npcDialogue_mid: '저는 고슴도치예요. 낯선 사람과 이야기하는 게 항상 쉽진 않지만... 당신은 괜찮아 보여서요.',
    npcDialogue_high: '안녕하세요. 저는 고슴도치예요. 사실 처음엔 말 걸기 어려웠는데, 대화하다 보면 편해지더라고요.',
    questionPrompt: '낯선 사람이 먼저 말을 걸어왔어요. 어떻게 했어요?',
    contextForAPI: '낯선 사람이 말을 거는 상황. E(외향성)이 높을수록 반갑게 대화를 이어가고, 낮을수록 조심스럽거나 짧게 응답한다.',
    nextSituationHint: '오늘 뜻밖의 기쁜 소식이 생긴 상황',
  },
  {
    id: '1-4',
    chapterIndex: 0,
    chapterType: 'E',
    chapterTitle: '광장 축제',
    chapterEmoji: '🌻',
    npcKey: 'quokka',
    npcName: '쿼카',
    narratorText: '오늘 아주 기쁜 일이 생겼어요! 쿼카가 눈을 반짝이며 물었어요.',
    npcDialogue_low: '좋은 일이 생기면 어떻게 해? 나는 당장 친구한테 달려가서 말하고 싶어지던데.',
    npcDialogue_mid: '기쁜 소식 있어? 나는 뭔가 좋은 일이 생기면 꼭 친구들이랑 나누고 싶더라고! 너는 어때?',
    npcDialogue_high: '기쁜 소식!! 기쁜 소식이 있으면 당장 다 같이 나눠야지!! 혼자 알고 있으면 너무 아깝잖아!!',
    questionPrompt: '기쁜 소식이 생겼을 때, 제일 먼저 뭘 하고 싶어요?',
    contextForAPI: '기쁜 소식을 공유하는 상황. E(외향성)이 높을수록 바로 친구들에게 알리고 싶어하고, 낮을수록 혼자 음미하거나 친한 한 사람에게만 말한다.',
    nextSituationHint: '하루 종일 광장을 돌아다녀 몸이 지쳐오는 상황',
  },
  {
    id: '1-5',
    chapterIndex: 0,
    chapterType: 'E',
    chapterTitle: '광장 축제',
    chapterEmoji: '🌻',
    npcKey: 'hedgehog',
    npcName: '고슴도치',
    narratorText: '하루 종일 광장을 돌아다녔더니 조금 지쳤어요. 고슴도치가 공감하듯 말했어요.',
    npcDialogue_low: '저는 피곤할 땐 꼭 혼자 있어야 해요. 조용한 방에서 책 읽거나... 그래야 충전이 되거든요.',
    npcDialogue_mid: '지칠 때 쉬는 방법은 사람마다 다른 것 같아요. 저는 주로 조용히 쉬는 편이에요. 당신은요?',
    npcDialogue_high: '지치면 여럿이서 먹고 마시면서 수다 떠는 게 오히려 활력이 될 수도 있어요. 저도 그럴 때가 있더라고요.',
    questionPrompt: '지쳤을 때 기운을 어떻게 충전해요?',
    contextForAPI: '에너지 충전 방법 상황. E(외향성)이 높을수록 사람들과 함께하며 충전하고, 낮을수록 혼자만의 시간으로 충전한다.',
    nextSituationHint: '광장에서의 시간을 마무리하며 숲길로 향하는 장면',
  },

  // ============================
  // 챕터 2: 반짝이 숲길 (O: 개방성)
  // ============================
  {
    id: '2-1',
    chapterIndex: 1,
    chapterType: 'O',
    chapterTitle: '반짝이 숲길',
    chapterEmoji: '🌿',
    npcKey: 'beaver',
    npcName: '비버',
    narratorText: '숲길을 걷다 보니 작고 예쁜 꽃 한 송이가 발밑에 피어있어요.',
    npcDialogue_low: '이 꽃... 어떤 느낌이에요? 저는 꽃잎이 5개이고 줄기가 3cm라는 건 알겠는데, 설명하기가 어려워요.',
    npcDialogue_mid: '이 꽃 봐요! 비버인 저는 꽃잎 개수랑 색깔을 먼저 세게 되더라고요. 당신은 어떤 걸 먼저 보나요?',
    npcDialogue_high: '이 꽃은 꽃잎이 정확히 5장이고요, 줄기 높이는 약 3.2cm, 색깔은 연보라색 계열이에요. 다 기록해뒀죠!',
    questionPrompt: '이 꽃, 어떤 느낌이에요? 🌸',
    contextForAPI: '작은 꽃을 관찰하는 상황. O(개방성)이 높을수록 꽃에서 이야기나 감정을 연상하고, 낮을수록 구체적인 특징을 관찰하는 데 집중한다.',
    nextSituationHint: '숲길 꼭대기에 올라 하늘의 구름을 바라보는 상황',
  },
  {
    id: '2-2',
    chapterIndex: 1,
    chapterType: 'O',
    chapterTitle: '반짝이 숲길',
    chapterEmoji: '🌿',
    npcKey: 'sheep',
    npcName: '아기 양',
    narratorText: '숲길 언덕에서 하늘을 바라보니 구름이 두둥실 떠 있어요.',
    npcDialogue_low: '저 구름... 저는 흰색 구름이라고밖에 안 보여요. 아기 양처럼 보인다는데 잘 모르겠어요.',
    npcDialogue_mid: '저 구름 봐요! 왠지 하늘을 나는 토끼 같지 않아요? 저는 구름 보면 항상 뭔가가 보여요.',
    npcDialogue_high: '저 구름은요! 왼쪽엔 고래가 있고요, 오른쪽엔 성이 있어요! 저기 봐요, 용도 있어요! 보여요??',
    questionPrompt: '저 구름, 뭔가로 보여요?',
    contextForAPI: '구름 바라보기 상황. O(개방성)이 높을수록 구름에서 이야기나 형상을 상상하고, 낮을수록 구름의 물리적 형태와 움직임을 관찰한다.',
    nextSituationHint: '숲길 아래로 내려가는 길에 갈림길이 나타난 상황',
  },
  {
    id: '2-3',
    chapterIndex: 1,
    chapterType: 'O',
    chapterTitle: '반짝이 숲길',
    chapterEmoji: '🌿',
    npcKey: 'beaver',
    npcName: '비버',
    narratorText: '숲길에 갈림길이 나타났어요. 한쪽은 팻말이 있는 안전한 길, 다른 쪽은 미지의 숲길이에요.',
    npcDialogue_low: '음... 지도는 있는데, 이 상황에서 어떻게 해야 할지 잘 모르겠어요.',
    npcDialogue_mid: '비버는 지도랑 표지판을 먼저 확인해요! 정보를 모으고 나서 결정하는 게 맞지 않을까요?',
    npcDialogue_high: '지도에 따르면 왼쪽이 맞아요! 표지판도 확인했고, 거리도 계산해봤어요. 이쪽으로 가면 됩니다!',
    questionPrompt: '갈림길이에요. 어떻게 하겠어요?',
    contextForAPI: '길 찾기 상황. O(개방성)이 높을수록 새로운 미지의 길을 탐험하고 싶어하고, 낮을수록 안전하고 익숙한 길을 선택한다.',
    nextSituationHint: '숲에서의 하루가 저물고, 아기 양이 일기장을 꺼내드는 상황',
  },
  {
    id: '2-4',
    chapterIndex: 1,
    chapterType: 'O',
    chapterTitle: '반짝이 숲길',
    chapterEmoji: '🌿',
    npcKey: 'sheep',
    npcName: '아기 양',
    narratorText: '숲에서의 하루가 저물어가요. 아기 양이 작은 일기장을 꺼내들었어요.',
    npcDialogue_low: '저는 오늘 있었던 일을 어떻게 기록할지 잘 모르겠어요. 그냥 그림만 그렸어요.',
    npcDialogue_mid: '저는 오늘 본 무지개를 일기에 그림으로 그렸어요. 말로 설명하면 색이 느껴지지 않거든요.',
    npcDialogue_high: '오늘 일기는 무지개 그림이랑 시랑 음악이랑 다 합쳐서 써야 할 것 같아요!! 느낌이 너무 풍부해서요!',
    questionPrompt: '오늘 하루를 어떻게 기억하고 싶어요?',
    contextForAPI: '하루 기록 상황. O(개방성)이 높을수록 감정이나 이미지를 창의적으로 표현하고, 낮을수록 구체적인 사건과 사실을 기록한다.',
    nextSituationHint: '마을 가게에서 조립이 필요한 선물을 받는 상황',
  },
  {
    id: '2-5',
    chapterIndex: 1,
    chapterType: 'O',
    chapterTitle: '반짝이 숲길',
    chapterEmoji: '🌿',
    npcKey: 'beaver',
    npcName: '비버',
    narratorText: '마을 가게에서 조립이 필요한 멋진 선물을 받았어요. 두꺼운 설명서도 함께 들어있어요.',
    npcDialogue_low: '설명서... 솔직히 두꺼워서 읽기 싫긴 한데, 안 읽으면 망칠 것 같아서요.',
    npcDialogue_mid: '비버는 설명서를 꼭 처음부터 끝까지 읽어야 해요. 그래야 제대로 할 수 있거든요!',
    npcDialogue_high: '설명서는 읽기 전에 목차부터 파악하고, 전체 흐름을 이해한 뒤 단계별로 정독해야 합니다!',
    questionPrompt: '설명서, 어떻게 할 것 같아요?',
    contextForAPI: '새 물건 조립 상황. O(개방성)이 높을수록 직관적으로 먼저 시도해보거나 자신만의 방법을 찾고, 낮을수록 설명서를 꼼꼼히 따른다.',
    nextSituationHint: '숲길을 마무리하고 호숫가 찻집으로 향하는 장면',
  },

  // ============================
  // 챕터 3: 호숫가 찻집 (A: 우호성)
  // ============================
  {
    id: '3-1',
    chapterIndex: 2,
    chapterType: 'A',
    chapterTitle: '호숫가 찻집',
    chapterEmoji: '☕',
    npcKey: 'maru',
    npcName: '리트리버 마루',
    narratorText: '찻집에서 차를 마시다가 친구가 실수로 예쁜 컵을 깨뜨렸어요.',
    npcDialogue_low: '어... 괜찮아. 다치진 않았지? 컵은... 음, 어떻게 하면 좋을까.',
    npcDialogue_mid: '마루는 바로 달려갈 것 같아요! 괜찮아? 다친 데 없어? 컵은 다시 사면 되니까 걱정 마!',
    npcDialogue_high: '괜찮아?? 다친 데 없어?? 마음이 아프겠다, 실수한 것 때문에 속상하지? 괜찮아, 다 괜찮아!!',
    questionPrompt: '친구가 실수로 컵을 깼어요. 어떻게 반응했어요?',
    contextForAPI: '친구의 실수에 대응하는 상황. A(우호성)이 높을수록 감정을 먼저 위로하고 공감하며, 낮을수록 상황 처리와 해결책을 먼저 생각한다.',
    nextSituationHint: '찻집에 맛있는 간식이 생겨서 여러 친구들과 나눠야 하는 상황',
  },
  {
    id: '3-2',
    chapterIndex: 2,
    chapterType: 'A',
    chapterTitle: '호숫가 찻집',
    chapterEmoji: '☕',
    npcKey: 'owl',
    npcName: '올빼미 선생님',
    narratorText: '찻집에 하나 남은 한정판 꿀케이크가 생겼어요. 여러 마을 친구들과 나눠야 하는 상황이에요.',
    npcDialogue_low: '나눌 때 기준이 딱히 없으면 어떻게 하는 게 좋을까요? 저는 잘 모르겠어요.',
    npcDialogue_mid: '올빼미 선생님은 공평하게 나눠야 한다고 생각해요. 그래야 아무도 상처받지 않으니까요.',
    npcDialogue_high: '간식 배분은 원칙이 있어야 합니다! 먼저 온 순서, 또는 균등 분배. 감정이 아닌 기준으로!',
    questionPrompt: '꿀케이크를 나눈다면 어떤 기준으로 할 것 같아요?',
    contextForAPI: '간식 나눔 기준 상황. A(우호성)이 높을수록 상황과 감정을 고려해 양보하고, 낮을수록 공정한 원칙과 기준을 적용한다.',
    nextSituationHint: '찻집 TV에서 슬픈 영화가 흘러나오는 상황',
  },
  {
    id: '3-3',
    chapterIndex: 2,
    chapterType: 'A',
    chapterTitle: '호숫가 찻집',
    chapterEmoji: '☕',
    npcKey: 'maru',
    npcName: '리트리버 마루',
    narratorText: '찻집 TV에서 아주 슬픈 영화가 흘러나오고 있어요.',
    npcDialogue_low: '나는 슬픈 영화 보면... 어, 눈물이 나려고 해. 이런 거 잘 안 보는 편이야.',
    npcDialogue_mid: '마루는 슬픈 영화 보면 꼭 눈물이 나. 같이 울어도 괜찮아! 눈물이 나는 게 자연스러운 거잖아.',
    npcDialogue_high: '슬픈 영화 보면서 펑펑 우는 건 당연한 거야!! 감정을 느끼는 게 살아있는 거잖아! 같이 울자!!',
    questionPrompt: '슬픈 영화, 어떤 반응이 나와요?',
    contextForAPI: '슬픈 영화 반응 상황. A(우호성)이 높을수록 감정에 충분히 공명하고, 낮을수록 내용을 분석하거나 감정적 거리를 둔다.',
    nextSituationHint: '찻집 앞 줄에서 기다리다 누군가 새치기를 하는 상황',
  },
  {
    id: '3-4',
    chapterIndex: 2,
    chapterType: 'A',
    chapterTitle: '호숫가 찻집',
    chapterEmoji: '☕',
    npcKey: 'owl',
    npcName: '올빼미 선생님',
    narratorText: '찻집 앞 줄에서 기다리고 있는데 갑자기 누군가 새치기를 했어요.',
    npcDialogue_low: '저도 이런 상황에서 어떻게 해야 할지 늘 고민이에요...',
    npcDialogue_mid: '올빼미 선생님은 정중하게 말할 것 같아요. 이건 규칙 위반이니까요. 단, 폭력적이지 않게요.',
    npcDialogue_high: '이건 명백한 규칙 위반입니다. 정중하지만 단호하게 "먼저 기다리던 분들이 계세요"라고 말해야죠.',
    questionPrompt: '새치기를 당했어요. 어떻게 했어요?',
    contextForAPI: '새치기 대응 상황. A(우호성)이 높을수록 상대방 입장을 이해하며 넘어가거나 부드럽게 말하고, 낮을수록 원칙에 따라 단호하게 대응한다.',
    nextSituationHint: '찻집에서 친구가 진지한 고민을 털어놓는 상황',
  },
  {
    id: '3-5',
    chapterIndex: 2,
    chapterType: 'A',
    chapterTitle: '호숫가 찻집',
    chapterEmoji: '☕',
    npcKey: 'maru',
    npcName: '리트리버 마루',
    narratorText: '찻집에서 친구가 심각한 고민을 털어놓기 시작했어요.',
    npcDialogue_low: '고민... 들어줄게. 어렵겠다. 뭔가 도움이 되고 싶은데 어떻게 해야 할지 모르겠어.',
    npcDialogue_mid: '마루는 일단 다 들어줄 것 같아요! 네 마음이 제일 중요하니까. 충분히 말해봐.',
    npcDialogue_high: '다 들을게! 어떤 이야기든 괜찮아! 네가 털어놓는 것만으로도 나는 기뻐! 같이 생각해볼게!!',
    questionPrompt: '친구의 고민, 어떻게 들어줄 것 같아요?',
    contextForAPI: '고민 상담 상황. A(우호성)이 높을수록 감정을 먼저 들어주고 위로하며, 낮을수록 해결책과 조언을 제시하려 한다.',
    nextSituationHint: '찻집을 떠나 간이역으로 향하는 장면',
  },

  // ============================
  // 챕터 4: 칙칙폭폭 간이역 (C: 성실성)
  // ============================
  {
    id: '4-1',
    chapterIndex: 3,
    chapterType: 'C',
    chapterTitle: '칙칙폭폭 간이역',
    chapterEmoji: '🚂',
    npcKey: 'raccoon',
    npcName: '너구리 역장',
    narratorText: '내일 여행을 가야 해요. 기차역 대합실에서 너구리 역장이 말했어요.',
    npcDialogue_low: '저도 짐 싸는 게 늘 마지막까지 미뤄지더라고요. 전날 밤에 부랴부랴 싸곤 해요.',
    npcDialogue_mid: '역장은 출발 전날까지 짐을 다 싸야 마음이 편해요. 당신은 언제 짐을 준비하나요?',
    npcDialogue_high: '역장은 3일 전부터 체크리스트 작성, 2일 전부터 짐 싸기 시작, 전날 최종 확인! 이게 정석이죠!',
    questionPrompt: '여행 짐, 언제 싸요?',
    contextForAPI: '여행 준비 상황. C(성실성)이 높을수록 미리 체계적으로 준비하고, 낮을수록 출발 직전이나 당일에 즉흥적으로 준비한다.',
    nextSituationHint: '타려던 기차가 갑자기 취소되는 상황',
  },
  {
    id: '4-2',
    chapterIndex: 3,
    chapterType: 'C',
    chapterTitle: '칙칙폭폭 간이역',
    chapterEmoji: '🚂',
    npcKey: 'squirrel',
    npcName: '다람쥐 여행가',
    narratorText: '타려던 기차가 갑자기 취소됐어요! 다람쥐 여행가가 눈을 반짝였어요.',
    npcDialogue_low: '어... 기차가 취소됐어요? 어떡하지... 이런 상황 너무 당황스럽다.',
    npcDialogue_mid: '다람쥐는 이런 예상치 못한 상황도 재미있을 수 있다고 생각해요! 다른 방법을 찾아볼게요!',
    npcDialogue_high: '오!! 기차 취소?! 이런 날이 오히려 더 신나는 모험이 되더라고요! 이제 뭘 해볼까요?!',
    questionPrompt: '기차가 취소됐어요! 어떻게 반응했어요?',
    contextForAPI: '예상치 못한 상황 대처. C(성실성)이 높을수록 당황하며 빠르게 대안 계획을 세우고, 낮을수록 유연하게 새로운 가능성을 받아들인다.',
    nextSituationHint: '기차역 대합실이 어수선하게 보이는 상황',
  },
  {
    id: '4-3',
    chapterIndex: 3,
    chapterType: 'C',
    chapterTitle: '칙칙폭폭 간이역',
    chapterEmoji: '🚂',
    npcKey: 'raccoon',
    npcName: '너구리 역장',
    narratorText: '기차역 대합실이 조금 어수선해 보여요. 너구리 역장이 청소함을 꺼내들었어요.',
    npcDialogue_low: '어수선한 거... 사실 저도 정리를 잘 못하는 편이에요. 어디서부터 해야 할지.',
    npcDialogue_mid: '모든 물건은 제자리가 있어야 해요! 역장의 역할은 기차역을 항상 정돈된 상태로 유지하는 거예요.',
    npcDialogue_high: '구역별 정리함 라벨링, 청소 주기 표 작성, 물건 배치 도면까지 완비해야 합니다! 체계가 안전이에요!',
    questionPrompt: '주변 공간, 어떻게 관리하는 편이에요?',
    contextForAPI: '정리 정돈 습관. C(성실성)이 높을수록 체계적이고 규칙적으로 정리하고, 낮을수록 필요할 때 그때그때 정리한다.',
    nextSituationHint: '여행 중 배가 고파져서 식사를 고민하는 상황',
  },
  {
    id: '4-4',
    chapterIndex: 3,
    chapterType: 'C',
    chapterTitle: '칙칙폭폭 간이역',
    chapterEmoji: '🚂',
    npcKey: 'squirrel',
    npcName: '다람쥐 여행가',
    narratorText: '여행 중 배가 고파졌어요. 다람쥐 여행가가 간식을 꺼내며 물었어요.',
    npcDialogue_low: '저는 식사 시간을 잘 지키는 편이 아니에요. 배고프면 먹는 거 아닌가요?',
    npcDialogue_mid: '다람쥐는 배고프면 먹으면 된다고 생각해요! 꼭 정해진 시간을 지켜야 할까요?',
    npcDialogue_high: '식사 시간 같은 건 상황에 맞게 자유롭게 하면 되죠! 시계보다 몸이 더 정직해요!',
    questionPrompt: '식사 시간, 어떻게 생각해요?',
    contextForAPI: '식사 시간과 루틴 상황. C(성실성)이 높을수록 정해진 시간과 루틴을 중요하게 여기고, 낮을수록 상황에 맞게 유연하게 생각한다.',
    nextSituationHint: '기차역 기념품점에서 조립이 필요한 기념품을 사는 상황',
  },
  {
    id: '4-5',
    chapterIndex: 3,
    chapterType: 'C',
    chapterTitle: '칙칙폭폭 간이역',
    chapterEmoji: '🚂',
    npcKey: 'raccoon',
    npcName: '너구리 역장',
    narratorText: '기차역 기념품점에서 조립이 필요한 예쁜 미니어처를 샀어요.',
    npcDialogue_low: '저도 이런 거 조립할 때... 솔직히 설명서 보면서도 헤매곤 해요.',
    npcDialogue_mid: '역장은 먼저 설명서를 다 읽고, 부품을 분류하고, 그 다음에 하나씩 조립해요!',
    npcDialogue_high: '설명서 통독 → 부품 카테고리별 분류 → 단계별 체크리스트 작성 → 조립 시작! 이 순서가 중요해요!',
    questionPrompt: '조립 기념품이에요. 어떻게 시작할 것 같아요?',
    contextForAPI: '새 작업 시작 방식. C(성실성)이 높을수록 단계를 명확히 하고 준비된 후 시작하고, 낮을수록 일단 시작해보며 진행한다.',
    nextSituationHint: '간이역에서의 여정을 마무리하며 비 내리는 정원으로 향하는 장면',
  },

  // ============================
  // 챕터 5: 비 내리는 정원 (N: 감수성/정서 안정성)
  // ============================
  {
    id: '5-1',
    chapterIndex: 4,
    chapterType: 'N',
    chapterTitle: '비 내리는 정원',
    chapterEmoji: '🌧️',
    npcKey: 'frog',
    npcName: '개구리',
    narratorText: '정원에 도착하자마자 갑자기 소나기가 쏟아지기 시작했어요.',
    npcDialogue_low: '소나기? 어, 그냥 비잖아요. 우산 없으면 좀 젖는 거고... 나는 어차피 젖어도 괜찮은데.',
    npcDialogue_mid: '비가 왔네요. 처마 밑에 잠깐 피할까요? 이러다 금방 그칠 수도 있으니까요.',
    npcDialogue_high: '어머, 소나기다!! 나는 갑작스러운 변화에 많이 당황해요... 빨리 어딘가 피해야 할 것 같아요!',
    questionPrompt: '갑자기 소나기가 쏟아졌어요. 어떤 마음이 들었어요? 🌧️',
    contextForAPI: '갑작스러운 소나기 상황. N(감수성)이 높을수록 당황하거나 감정 동요가 크고, 낮을수록 담담하게 받아들인다.',
    nextSituationHint: '처마 밑에서 기다리다 달팽이가 빗속을 느긋하게 걷고 있는 장면',
  },
  {
    id: '5-2',
    chapterIndex: 4,
    chapterType: 'N',
    chapterTitle: '비 내리는 정원',
    chapterEmoji: '🌧️',
    npcKey: 'snail',
    npcName: '달팽이',
    narratorText: '달팽이가 빗속을 느긋하게 걸어오고 있어요. 천둥이 우르릉 울렸어요.',
    npcDialogue_low: '천둥소리... 나는 별로 신경 쓰이지 않아요. 그냥 큰 소리잖아요.',
    npcDialogue_mid: '천둥이 크게 울렸네요. 조금 놀랐지만 괜찮아요. 달팽이는 어디서든 집이 있으니까요.',
    npcDialogue_high: '우르릉..!! 저도 천둥 소리에 많이 놀랐어요. 심장이 쿵했거든요. 당신은 괜찮았어요?',
    questionPrompt: '천둥이 쾅 울렸어요. 어떻게 됐어요?',
    contextForAPI: '천둥소리 반응 상황. N(감수성)이 높을수록 강하게 놀라거나 불안해하고, 낮을수록 덤덤하게 반응한다.',
    nextSituationHint: '비가 조금 잦아들며 빗소리가 리듬감 있게 들려오는 장면',
  },
  {
    id: '5-3',
    chapterIndex: 4,
    chapterType: 'N',
    chapterTitle: '비 내리는 정원',
    chapterEmoji: '🌧️',
    npcKey: 'snail',
    npcName: '달팽이',
    narratorText: '비가 조금 잦아들었어요. 빗방울이 나뭇잎을 두드리는 소리가 들렸어요.',
    npcDialogue_low: '조용하네요. 비 오는 날은 그냥 조용히 있을 수 있어서 좋아요.',
    npcDialogue_mid: '빗소리를 들으면 뭔가 차분해지는 기분이에요. 달팽이인 저는 비가 정말 좋아요.',
    npcDialogue_high: '빗소리가 이렇게 다양할 줄 몰랐어요! 큰 빗방울 소리, 작은 빗방울 소리... 온 세상이 연주를 하는 것 같아요!',
    questionPrompt: '빗소리를 듣고 있어요. 어떤 기분이에요?',
    contextForAPI: '빗소리 감상 상황. N(감수성)이 높을수록 빗소리에서 풍부한 감정을 느끼고, 낮을수록 단순하고 담담하게 받아들인다.',
    nextSituationHint: '개구리가 걱정스러운 표정으로 뭔가 고민하는 장면',
  },
  {
    id: '5-4',
    chapterIndex: 4,
    chapterType: 'N',
    chapterTitle: '비 내리는 정원',
    chapterEmoji: '🌧️',
    npcKey: 'frog',
    npcName: '개구리',
    narratorText: '개구리가 작은 목소리로 말했어요. 오늘 아무 이유 없이 마음이 좀 무거운 날이라고.',
    npcDialogue_low: '아무 이유 없이 기분이 나쁜 날은... 저는 잘 모르겠어요. 그냥 흘려보내면 되는 거 아닌가요?',
    npcDialogue_mid: '이유 없이 기분이 안 좋은 날이 있잖아요. 그럴 땐 어떻게 하는 게 좋을까요?',
    npcDialogue_high: '이유도 모르게 마음이 무거운 날이 있어요. 그 감정 자체를 충분히 느끼는 게 중요한 것 같기도 하고...',
    questionPrompt: '아무 이유 없이 마음이 무거운 날, 어떻게 해요?',
    contextForAPI: '이유 없는 감정적 불편함 상황. N(감수성)이 높을수록 감정을 예민하게 느끼고 반추하며, 낮을수록 빠르게 털어내거나 무시한다.',
    nextSituationHint: '비가 그치고 구름 사이로 햇살이 비치는 장면',
  },
  {
    id: '5-5',
    chapterIndex: 4,
    chapterType: 'N',
    chapterTitle: '비 내리는 정원',
    chapterEmoji: '🌧️',
    npcKey: 'frog',
    npcName: '개구리',
    narratorText: '비가 그치고 구름 사이로 따뜻한 햇살이 스며들었어요.',
    npcDialogue_low: '비가 그쳤군요. 이제 나가도 되겠어요. 별거 아닌데 긴장했나 봐요.',
    npcDialogue_mid: '비 그친 후의 냄새가 참 좋아요. 페트리코르라고 하던가요. 땅이 기지개 켜는 냄새 같아서.',
    npcDialogue_high: '비 그친 후 공기가... 달라요! 뭔가 씻겨나간 것 같기도 하고, 세상이 새로 태어난 것 같기도 하고. 감동이에요.',
    questionPrompt: '비가 그쳤어요. 이 순간을 어떻게 느꼈어요?',
    contextForAPI: '날씨 변화 후 감정 반응. N(감수성)이 높을수록 날씨 변화에서 풍부하고 깊은 감정적 의미를 찾고, 낮을수록 단순하게 상황을 인식한다.',
    nextSituationHint: '정원에서의 시간을 마무리하며 마을 여행의 끝을 맞이하는 장면',
  },
];

// API 실패 시 폴백 편지 (챕터별 대표 NPC)
const FALLBACK_LETTERS = {
  chapter1: {
    npcKey: 'quokka',
    npcName: '쿼카',
    content: `안녕, 새 친구! 나 쿼카야 🌻\n\n광장에서 네가 조심스레 다가왔던 게 기억나. 처음엔 말 거는 게 쉽지 않아도, 결국 네가 마음을 열어줘서 정말 기뻤어.\n\n어떤 모습이든 괜찮아. 시끌벅적하게 어울리는 것도, 조용히 마음을 나누는 것도 다 소중한 방식이거든.\n\n언제든 광장에 오면 내가 가장 먼저 달려나갈게! 👋\n\n항상 응원해,\n쿼카가 💛`,
  },
  chapter2: {
    npcKey: 'sheep',
    npcName: '아기 양',
    content: `안녕하세요, 숲길에서 만난 친구님! 🌿\n\n같이 구름 보면서 이야기 나눴던 거 기억해요? 당신이 세상을 바라보는 방식이 정말 특별했어요.\n\n세상에는 꼼꼼하게 관찰하는 눈도 필요하고, 큰 그림을 그리는 상상력도 필요해요. 당신의 방식이 옳아요.\n\n숲길에 봄꽃이 피면 같이 보러 와요 🌸\n\n포근하게,\n아기 양이 🐑`,
  },
  chapter3: {
    npcKey: 'maru',
    npcName: '리트리버 마루',
    content: `안녕, 찻집 친구! ☕\n\n함께 차 마시면서 이야기 나눴던 시간이 정말 따뜻했어. 네가 친구 이야기를 들을 때 보였던 진심이 느껴졌거든.\n\n따뜻하게 공감하는 것도, 논리적으로 조언하는 것도 다 사랑의 방식이야. 네 방식이 최고야.\n\n언제든 차 한 잔 하러 와! 내가 기다릴게 🐕\n\n마음을 담아,\n마루가 🧡`,
  },
  chapter4: {
    npcKey: 'raccoon',
    npcName: '너구리 역장',
    content: `안녕하세요, 기차역을 찾아주신 여행자님! 🚂\n\n예상치 못한 기차 취소에도 당황하지 않으셨잖아요. 대단해요.\n\n계획적으로 준비하는 것도, 유연하게 흘러가는 것도 모두 여행의 지혜예요. 어떤 방식이든 결국 목적지에 도착하니까요.\n\n다음 여행도 이 역에서 출발하세요. 역장이 항상 기다리겠습니다 🦝\n\n안전한 여정을 바라며,\n너구리 역장이 🤎`,
  },
  chapter5: {
    npcKey: 'snail',
    npcName: '달팽이',
    content: `안녕하세요, 비 내리는 정원에서 만난 분! 🌧️\n\n저는 달팽이예요. 비가 오든 해가 뜨든, 느긋하게 걷는 게 제 삶의 방식이에요.\n\n당신이 빗소리에 귀 기울이던 순간이 기억나요. 그 작은 감수성이 세상을 더 풍요롭게 만들어요.\n\n자신의 감정을 느끼는 것, 그것은 용기 있는 일이에요. 당신의 감수성은 선물이에요 🌿\n\n촉촉한 마음으로,\n달팽이가 💌`,
  },
};
